# Configuration file for scheduler-simulator

# This is an example config for scheduler-simulator.

apiVersion: kube-scheduler-simulator-config/v1alpha1
kind: SimulatorConfiguration

# This is the port number on which kube-scheduler-simulator
# server is started.
port: 1212

# This is the URL for etcd. The simulator runs kube-apiserver
# internally, and the kube-apiserver uses this etcd.
etcdURL: "http://127.0.0.1:2379"

# This URL represents the URL once web UI is started.
# The simulator and internal kube-apiserver set the allowed
# origin for CorsAllowedOriginList
corsAllowedOriginList:
  - "http://localhost:3000"

# This is for the beta feature "One-shot importing cluster's resources",
# "Continuous syncing cluster's resources" and "Recording cluster's events".
# This variable is used to find Kubeconfig required to access your
# cluster for importing resources to scheduler simulator.
kubeConfig: "/kubeconfig.yaml"

# This is the url of kube-apiserver.
# This variable is used to connect to the user cluster's kube-apiserver.
kubeApiServerUrl: ""

# The path to a KubeSchedulerConfiguration file.
# If passed, the simulator will start the scheduler
# with that configuration. Or, if you use web UI,
# you can change the configuration from the web UI as well.
kubeSchedulerConfigPath: ""

# This variable indicates whether the simulator will
# import resources from a user cluster specified by kubeConfig.
# Note that it only imports the resources once when the simulator is started.
# You cannot make two or more of externalImportEnabled, resourceSyncEnabled and replayEnabled true
# because those features would be conflicted.
# This is still a beta feature.
externalImportEnabled: false

# This variable indicates whether the simulator will
# keep syncing resources from an user cluster's or not.
# You cannot make two or more of externalImportEnabled, resourceSyncEnabled and replayEnabled true
# because those features would be conflicted.
# Note, this is still a beta feature.
resourceSyncEnabled: false

# This variable indicates whether the simulator will
# record events from a user cluster specified by kubeConfig.
# You cannot make both of recorderEnabled and replayEnabled true because those features would be conflicted.
# Note, this is still a beta feature.
recorderEnabled: false

# This variable indicates whether the simulator will
# replay events recorded in the file specified by recordFilePath.
# You cannot make two or more of externalImportEnabled, resourceSyncEnabled and replayEnabled true
# because those features would be conflicted.
# You cannot make both of recorderEnabled and replayEnabled true because those features would be conflicted.
# Note, this is still a beta feature.
replayEnabled: true

# The path to a file which the simulator will record
# events to or replay events from.
recordFilePath: "./simulator/record"
