name: Lint Frontend

on:
  push:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "web"

env:
  YARN_CACHE_FOLDER: .cache/yarn

jobs:
  lint:
    name: lint frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Setup Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn run lint
